#!/usr/bin/env bash

dir=$(dirname $(readlink $BASH_SOURCE))

subcmd=

while [ "$1" != "" ]; do
  subcmd="$subcmd $1"
  shift
done

cmd=$(node $dir/dk.js $(basename $(pwd)) --cwd=$(pwd)$subcmd)
echo "\$ $cmd"
eval $cmd

